name: Cettia
description: Cettia, the real-time web application framework.
url: http://cettia.io
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
relative_permalinks: false
permalink: /blog/:title/
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
sass:
    style: compressed
