name: Cettia
title: Cettia
description: Cettia is a full-featured real-time web application framework that you can use to exchange events between server and client in real-time.
url: https://cettia.io
author:
  name: Donghwan Kim
  email: flowersinthesand@gmail.com
  twitter: flowersits
permalink: /blog/:title/
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
sass:
    style: compressed
twitter:
  username: flowersits
social:
  links:
    - https://github.com/cettia
    - https://twitter.com/flowersits
    - http://groups.google.com/group/cettia
