name: Cettia
description: Cettia, the real-time web application framework.
url: http://cettia.io/
relative_permalinks: false
permalink: /blog/:title/
paginate: 5
paginate_path: "/blog/page:num"
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables